meta_product_name: "Work In Tech"
meta_title: "Work In Tech - Découvrez les métiers de l'informatique"
meta_description: "Site pour découvrir les différents métiers de l'informatique"
meta_image: "og.png" # should exist in `app/assets/images/`
