meta_product_name: "Work in Tech"
meta_title: "Work in Tech - Découvre les métiers de la tech en t'amusant."
meta_description: "Jeux interactifs et fiches métiers pour préparer ton avenir."
meta_image: "og.png" # should exist in `app/assets/images/`
